### ISSUE TITLE
Update README.md with the latest client delcaration related changes

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/graphql-tools#100]
**Description:**
$subject should be done with the changes introduced by https://github.com/ballerina-platform/graphql-tools/pull/94

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by udda1996** [comment]
This should include the changes introduced by #99
