### ISSUE TITLE
Investigate on a way to define a security schema while generating the client

### ISSUE THREAD

**Issue by abeykoon** [ballerina-platform/graphql-tools#158]
**Description:**

When we generate a GraphQL client pointing to a particular SDL definition and queries.graphql file, the generated client does not contain any security information. But practically, GraphQL calls are secured. 

We need to identify a way to define security when generating a client. Does SDL provide a way for this? 

In my case, I had to edit the client by hand, and also I missed one point to edit, which led me to debug the code and understand why it was not working. 

**Affected Product Version:**

Ballerina 2201.4.1

**OS, DB, other environment details and versions:**    
Mac OS

**Steps to reproduce:**
Pls see above 

**Related Issues:**
https://github.com/wso2-enterprise/choreo/issues/19688

**Comment by abeykoon** [comment]
@shafreenAnfar do we have any plan on this?

**Comment by shafreenAnfar** [comment]
I don't think GraphQL SDL capture those info. @ThisaruGuruge

**Comment by ThisaruGuruge** [comment]
Yes, the GraphQL schema does not capture that information. Security information depends on the server implementation and does not affect the GraphQL schema. In most cases, the security-related functionalities are done by the HTTP layer so the GraphQL service does not have any knowledge of it. There's no way of capturing this on the client side, by looking at the schema. Therefore, I don't think we can capture this information when generating a client.
